### PR TITLE
feat: enhance openai prompt

### LINKED ISSUE #141: openai prompt增强建议
原Prompt作为systemPrompt，引入userPrompt进行强约束（可以参考沉浸式翻译）
参考修改逻辑：
1、界面修改为systemPrompt和userPrompt
2、openai默认配置设置为：
```js
const defaultOpenaiApi = {
  url: "https://api.openai.com/v1/chat/completions",
  key: "", 
  model: "gpt-4",
  systemPrompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
  prompt: `Translate the following source text to ${INPUT_PLACE_TO}, Output translation directly without any additional text.\nSource Text: ${INPUT_TEXT}\nTranslated Text:`,
  temperature: 0,
  maxTokens: 256,
  fetchLimit: 1,
  fetchInterval: 500,
};
```
3、请求更改为：
```js
const genOpenAI = ({
	text,
	from,
	to,
	url,
	key,
	prompt,
	model,
	temperature,
	maxTokens,
}) => {
	systemPrompt = systemPrompt
		.replaceAll(INPUT_PLACE_FROM, from)
		.replaceAll(INPUT_PLACE_TO, to);

	prompt = prompt
		.replaceAll(INPUT_PLACE_TO, to)
		.replaceAll(INPUT_TEXT, text);
        
	const data = {
		model,
		messages: [
			{
				role: "system",
				content: systemPrompt,
			},
			{
				role: "user",
				content: prompt,
			},
		],
		temperature,
		max_tokens: maxTokens,
	};

	const init = {
		headers: {
			"Content-type": "application/json",
			Authorization: `Bearer ${key}`, // OpenAI
			"api-key": key, // Azure OpenAI
		},
		method: "POST",
		body: JSON.stringify(data),
	};

	return [url, init];
};

```

### PR DESCRIPTION
**Pull request by hoilc**
Close #141

根据 #185 #141 建议，对OpenAI prompt进行双重约束

默认请求示例

```
[{
	"role": "system",
	"content": "You are a professional, authentic machine translation engine. You will be provided with a sentence in English, and your task is to translate it into Simplified Chinese."
}, {
	"role": "user",
	"content": "Translate the following source text from English to Simplified Chinese. Output translation directly without any additional text.\n\nSource Text: hello world\n\nTranslated Text:"
}]
```

为兼容历史上作为systemPrompt的prompt，如果prompt中不包含带翻译文本，则添加文本到prompt末尾

```
[{
	"role": "system",
	"content": "You are a professional, authentic machine translation engine. You will be provided with a sentence in English, and your task is to translate it into Simplified Chinese."
}, {
	"role": "user",
	"content": "You will be provided with a sentence in English, and your task is to translate it into Simplified Chinese.\nSource Text: hello world"
}]
```

### CODE REVIEW

**Comment by fishjar** [comment]
我将暂时先合并你的版本，但考虑到更平滑、简洁的兼容性，字段命名上，之前的`prompt`还是默认为`systemPrompt`，无需改动，然后添加新的`userPrompt`字段也许更好。

兼容性主要是考虑：用户升级到了新版本，但是API的配置并没有及时重新设置的情况。

按照你目前的更新，API参数经过一次浅合并后：

https://github.com/fishjar/kiss-translator/blob/d27b9c7f2d665ce04f8903db67a9a1f2c9d85aa7/src/hooks/Translate.js#L49-L52


大概如下：

```js
{
prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
systemPrompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
}
```

再经过如下替换：

```js
 if (!prompt.includes(INPUT_PLACE_TEXT)) {
    prompt += `\nSource Text: ${INPUT_PLACE_TEXT}`;
  }
```

最终如下：

```js
{
prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.\nSource Text: ${INPUT_PLACE_TEXT}`,
systemPrompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
}
```

如果是采用增加`userPrompt`的方案，API参数经过一次浅合并后大概如下：

```js
{
prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
userPrompt: `Translate the following source text from ${INPUT_PLACE_FROM} to ${INPUT_PLACE_TO}. Output translation directly without any additional text.\n\nSource Text: ${INPUT_PLACE_TEXT}\n\nTranslated Text:`,
}
```

可见，离升级后的推荐格式：

```js
{
prompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
userPrompt: `Translate the following source text from ${INPUT_PLACE_FROM} to ${INPUT_PLACE_TO}. Output translation directly without any additional text.\n\nSource Text: ${INPUT_PLACE_TEXT}\n\nTranslated Text:`,
}
```

很接近了，无需如下判断代码即有很好的兼容性：

```js
 if (!prompt.includes(INPUT_PLACE_TEXT)) {
    prompt += `\nSource Text: ${INPUT_PLACE_TEXT}`;
  }
```

**Comment by fishjar** [comment]
另外 `OPT_TRANS_CLAUDE` 的字段也可以统一，采用 `prompt`和`userPrompt`的命名。

**Comment by hoilc** [comment]
> 我将暂时先合并你的版本，但考虑到更平滑、简洁的兼容性，字段命名上，之前的`prompt`还是默认为`systemPrompt`，无需改动，然后添加新的`userPrompt`字段也许更好。
> 
> 兼容性主要是考虑：用户升级到了新版本，但是API的配置并没有及时重新设置的情况。
> 
> 按照你目前的更新，API参数经过一次浅合并后：
> 
> https://github.com/fishjar/kiss-translator/blob/d27b9c7f2d665ce04f8903db67a9a1f2c9d85aa7/src/hooks/Translate.js#L49-L52
> 
> 大概如下：
> 
> ```js
> {
> prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> systemPrompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> }
> ```
> 
> 再经过如下追加：
> 
> ```js
>  if (!prompt.includes(INPUT_PLACE_TEXT)) {
>     prompt += `\nSource Text: ${INPUT_PLACE_TEXT}`;
>   }
> ```
> 
> 最终如下：
> 
> ```js
> {
> prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.\nSource Text: ${INPUT_PLACE_TEXT}`,
> systemPrompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> }
> ```
> 
> 如果是采用增加`userPrompt`的方案，API参数经过一次浅合并后大概如下：
> 
> ```js
> {
> prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> userPrompt: `Translate the following source text from ${INPUT_PLACE_FROM} to ${INPUT_PLACE_TO}. Output translation directly without any additional text.\n\nSource Text: ${INPUT_PLACE_TEXT}\n\nTranslated Text:`,
> }
> ```
> 
> 可见，离升级后的推荐格式：
> 
> ```js
> {
> prompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> userPrompt: `Translate the following source text from ${INPUT_PLACE_FROM} to ${INPUT_PLACE_TO}. Output translation directly without any additional text.\n\nSource Text: ${INPUT_PLACE_TEXT}\n\nTranslated Text:`,
> }
> ```
> 
> 很接近了，无需如下代码即有很好的兼容性：
> 
> ```js
>  if (!prompt.includes(INPUT_PLACE_TEXT)) {
>     prompt += `\nSource Text: ${INPUT_PLACE_TEXT}`;
>   }
> ```

确实，去掉隐藏的判断比较好

也许可以完全使用`userPrompt`和`systemPrompt`，升级体验为重置成默认值

**Comment by fishjar** [comment]
> > 我将暂时先合并你的版本，但考虑到更平滑、简洁的兼容性，字段命名上，之前的`prompt`还是默认为`systemPrompt`，无需改动，然后添加新的`userPrompt`字段也许更好。
> > 兼容性主要是考虑：用户升级到了新版本，但是API的配置并没有及时重新设置的情况。
> > 按照你目前的更新，API参数经过一次浅合并后：
> > https://github.com/fishjar/kiss-translator/blob/d27b9c7f2d665ce04f8903db67a9a1f2c9d85aa7/src/hooks/Translate.js#L49-L52
> > 
> > 大概如下：
> > ```js
> > {
> > prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> > systemPrompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 再经过如下追加：
> > ```js
> >  if (!prompt.includes(INPUT_PLACE_TEXT)) {
> >     prompt += `\nSource Text: ${INPUT_PLACE_TEXT}`;
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 最终如下：
> > ```js
> > {
> > prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.\nSource Text: ${INPUT_PLACE_TEXT}`,
> > systemPrompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果是采用增加`userPrompt`的方案，API参数经过一次浅合并后大概如下：
> > ```js
> > {
> > prompt: `You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> > userPrompt: `Translate the following source text from ${INPUT_PLACE_FROM} to ${INPUT_PLACE_TO}. Output translation directly without any additional text.\n\nSource Text: ${INPUT_PLACE_TEXT}\n\nTranslated Text:`,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可见，离升级后的推荐格式：
> > ```js
> > {
> > prompt: `You are a professional, authentic machine translation engine. You will be provided with a sentence in ${INPUT_PLACE_FROM}, and your task is to translate it into ${INPUT_PLACE_TO}.`,
> > userPrompt: `Translate the following source text from ${INPUT_PLACE_FROM} to ${INPUT_PLACE_TO}. Output translation directly without any additional text.\n\nSource Text: ${INPUT_PLACE_TEXT}\n\nTranslated Text:`,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 很接近了，无需如下代码即有很好的兼容性：
> > ```js
> >  if (!prompt.includes(INPUT_PLACE_TEXT)) {
> >     prompt += `\nSource Text: ${INPUT_PLACE_TEXT}`;
> >   }
> > ```
> 
> 确实，去掉隐藏的判断比较好
> 
> 也许可以完全使用`userPrompt`和`systemPrompt`，升级体验为重置成默认值

废弃旧字段，强制使用新字段的默认值，可能会使得部分用户`丢失数据`——旧的个性化`prompt`。
另外还有几个API也用到了`prompt`参数，改动会比较多。

**Pull request merged**
